### ISSUE TITLE
Please add Code license

### ISSUE THREAD

**Issue by aihill** [FilippoMB/Reservoir-Computing-framework-for-multivariate-time-series-classification#1]
Hi  thanks for providing the code in github. As I don't know other ways to reach you , I am raising this as an issue. But my query is can we use your code for testing and if we use it for any competitions.may be adding a license info will benefit people like me. Thank you

**Comment by FilippoMB** [comment]
Thanks for bringing this issue to my attention.
I've added a MIT license to the software library.

**Comment by aihill** [comment]
Thank you very much.
