### ISSUE TITLE
Test dataset is used in training in the example? classification_example.py

### ISSUE THREAD

**Issue by 266918** [FilippoMB/Reservoir-Computing-framework-for-multivariate-time-series-classification#6]
The examples show it's using the full 640 MTS-"X" for training and then use 370 of them - "Xte" to test. Isn't Xte a subset of X?

**Comment by FilippoMB** [comment]
"X" contains only the first 270 MTS, which are used for training

>> data['X'].shape
>> (270, 29, 12)

while for testing, I am using the last 370 MTS

>> data['Xte'].shape
>> (370, 29, 12)

So, no overlap between train and test :)

**Comment by FilippoMB** [comment]
I updated the name of the variable "X" ---> "Xtr".
Hopefully, this will avoid confusion
